export enum Bears {
    POLAR_BEAR='POLAR_BEAR',
    GIANT_PANDA='GIANT_PANDA',
    SUN_BEAR='SUN_BEAR',
    BROWN_BEAR='BROWN_BEAR',
    AMERICAN_BLACK_BEAR='AMERICAN_BLACK_BEAR',
    ASIAN_BLACK_BEAR='ASIAN_BLACK_BEAR',
    SPECTACLED_BEAR='SPECTACLED_BEAR',
    SLOTH_BEAR='SLOTH_BEAR'
}
